file_patterns: &file_patterns
  - '**/*'
  - '!**/*.lock'
  - '!**/LICENSE'
  - '!**/*.md'

size/xs:
  max: 20
  files: *file_patterns

size/s:
  min: 21
  max: 50
  files: *file_patterns

size/m:
  min: 51
  max: 100
  files: *file_patterns

size/l:
  min: 101
  max: 300
  files: *file_patterns

size/xl:
  min: 301
  files: *file_patterns
