# =========================
# 1. Builder stage
# =========================
FROM registry.access.redhat.com/ubi9/ubi:9.6 AS builder

ARG USER=rhoai
ARG HOME=/home/${USER}
ARG TESTS_DIR=${HOME}/opendatahub-tests

ENV HOME=${HOME}
ENV PYTHONUNBUFFERED=1
ENV PATH="${HOME}/.local/bin:${PATH}"

ENV UV_COMPILE_BYTECODE=1
ENV UV_NO_CACHE=1
ENV UV_NO_SYNC=0

RUN dnf install -y \
        python3 python3-pip \
        git wget \
        gcc gcc-c++ make \
        pkgconf-pkg-config \
        openblas openblas-devel \
        openssl openssl-devel \
        zlib zlib-devel \
        rust cargo \
        perl perl-core \
    && dnf clean all \
    && rm -rf /var/cache/dnf

# Use system OpenSSL (fixes boringssl crash)
ENV OPENSSL_NO_VENDOR=1
ENV OPENSSL_DIR=/usr


# Force grpcio to use system SSL instead of boringssl
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
ENV GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1


# Reduce memory usage for numpy build
ENV NINJAFLAGS="-j1"
ENV CMAKE_BUILD_PARALLEL_LEVEL=1

ENV GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=3

RUN useradd -m -s /bin/bash ${USER}

USER ${USER}
WORKDIR ${HOME}


# install uv + pip tooling
RUN python3 -m pip install --user uv

WORKDIR ${TESTS_DIR}

COPY --chown=${USER}:${USER} . ${TESTS_DIR}

# install full environment
RUN uv lock && uv sync


# =========================
# 2. Runtime stage
# =========================
FROM registry.access.redhat.com/ubi9/ubi:9.6

ARG USER=rhoai
ARG HOME=/home/${USER}
ARG TESTS_DIR=${HOME}/opendatahub-tests

ENV HOME=${HOME}
ENV PATH="${HOME}/.local/bin:${PATH}"
ENV PYTHONUNBUFFERED=1

RUN dnf install -y \
        python3 python3-pip \
        openssl \
    && dnf clean all \
    && rm -rf /var/cache/dnf

# create user
RUN useradd -m -s /bin/bash ${USER}

# copy installed env from builder
COPY --from=builder --chown=${USER}:${USER} ${HOME} ${HOME}

USER ${USER}
WORKDIR ${TESTS_DIR}

ENTRYPOINT ["uv", "run", "pytest"]
