[tool.ruff]
preview = true
line-length = 120
fix = true
output-format = "grouped"

[tool.ruff.format]
exclude = [".git", ".venv", ".mypy_cache", ".tox", "__pycache__"]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_unused_ignores = true

[tool.uv]
dev-dependencies = [
    "ipdb>=0.13.13",
    "ipython>=8.12.3",
]

[project]
requires-python = ">=3.8"
name = "opendatahub-tests"
version = "0.1.0"
description = "Tests repository for Open Data Hub (ODH)"
authors = []
license = {text = "Apache License (2.0)"}
readme = "README.md"
keywords = ["Openshift", "RHOAI", "ODH"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]

dependencies = [
    "openshift-python-utilities",
    "openshift-python-wrapper",
    "pytest-progress",
    "pytest-testconfig",
    "python-simple-logger",
    "pyyaml",
    "syrupy>=4.0.1",
    "caikit-nlp-client>=0.0.8",
    "requests>=2.31.0",
    "aiohttp>=3.8.5",
    "pytest-asyncio>=0.21.1",
]

[project.urls]
homepage = "https://github.com/opendatahub-io/opendatahub-tests"
