# Generated by resource-generator — do not edit manually.
"""ConfigMap resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class ConfigMap(NamespaceScopedResource):
    """ConfigMap holds configuration data for pods to consume."""

    def __init__(
        self,
        binary_data: dict[str, str] | None = None,
        data: dict[str, str] | None = None,
        immutable: bool | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            binary_data (dict[str, str]): BinaryData contains the binary data.
                Each key must consist of alphanumeric characters, '-', '_' or '.'.
            data (dict[str, str]): Data contains the configuration data.
                Each key must consist of alphanumeric characters, '-', '_' or '.'.
            immutable (bool): Immutable, if set to true, ensures that data stored in the
                ConfigMap cannot be updated (only object metadata can be modified).
        """
        super().__init__(**kwargs)
        self.binary_data = binary_data
        self.data = data
        self.immutable = immutable

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        if self.binary_data is not None:
            resource["binaryData"] = self.binary_data
        if self.data is not None:
            resource["data"] = self.data
        if self.immutable is not None:
            resource["immutable"] = self.immutable

        return resource
