# Generated by resource-generator — do not edit manually.
"""DataScienceCluster resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.cluster_scoped_resource import ClusterScopedResource


class DataScienceCluster(ClusterScopedResource):
    """DataScienceCluster is the Schema for the datascienceclusters API."""

    api_group: str = "datasciencecluster.opendatahub.io"
    api_version: str = "v2"

    def __init__(
        self,
        components: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            components (dict[str, Any]): Override and fine tune specific component configurations.
        """
        super().__init__(**kwargs)
        self.components = components

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.components is not None:
            spec["components"] = self.components
        if spec:
            resource["spec"] = spec

        return resource
