# Generated by resource-generator — do not edit manually.
"""Endpoints resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class Endpoints(NamespaceScopedResource):
    """Endpoints is a collection of endpoints that implement the actual service.

    Endpoints is a legacy API and does not contain information about all Service features.
    Use discoveryv1.EndpointSlice for complete information about Service endpoints.
    Deprecated: This API is deprecated in v1.33+. Use discoveryv1.EndpointSlice.
    """

    def __init__(
        self,
        subsets: list[Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            subsets (list[Any]): The set of all endpoints is the union of all subsets.
                Addresses are placed into subsets according to the IPs they share.
        """
        super().__init__(**kwargs)
        self.subsets = subsets

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        if self.subsets is not None:
            resource["subsets"] = self.subsets

        return resource
