# Generated by resource-generator — do not edit manually.
"""Group resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.cluster_scoped_resource import ClusterScopedResource


class Group(ClusterScopedResource):
    """Group represents a referenceable set of Users.

    Compatibility level 1: Stable within a major release for a minimum of 12 months
    or 3 minor releases (whichever is longer).
    """

    api_group: str = "user.openshift.io"
    api_version: str = "v1"

    def __init__(
        self,
        users: list[str] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            users (list[str]) (required): users is the list of users in this group.
        """
        super().__init__(**kwargs)
        self.users = users

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        resource["users"] = self.users

        return resource
