# Generated by resource-generator — do not edit manually.
"""HTTPRoute resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class HTTPRoute(NamespaceScopedResource):
    """HTTPRoute provides a way to route HTTP requests.

    This includes the capability to match requests by hostname, path, header, or query param.
    Filters can be used to specify additional processing steps.
    Backends specify where matching requests should be routed.
    """

    api_group: str = "gateway.networking.k8s.io"
    api_version: str = "v1"

    def __init__(
        self,
        hostnames: list[str] | None = None,
        parent_refs: list[Any] | None = None,
        rules: list[Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            hostnames (list[str]): Hostnames defines a set of hostnames that should match
                against the HTTP Host header to select a HTTPRoute used to process the request.
            parent_refs (list[Any]): ParentRefs references the resources (usually Gateways)
                that a Route wants to be attached to.
            rules (list[Any]): Rules are a list of HTTP matchers, filters and actions.
        """
        super().__init__(**kwargs)
        self.hostnames = hostnames
        self.parent_refs = parent_refs
        self.rules = rules

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.hostnames is not None:
            spec["hostnames"] = self.hostnames
        if self.parent_refs is not None:
            spec["parentRefs"] = self.parent_refs
        if self.rules is not None:
            spec["rules"] = self.rules
        if spec:
            resource["spec"] = spec

        return resource
