# Generated by resource-generator — do not edit manually.
"""InferenceService resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class InferenceService(NamespaceScopedResource):
    """<empty>"""

    api_group: str = "serving.kserve.io"
    api_version: str = "v1beta1"

    def __init__(
        self,
        canary: list[Any] | None = None,
        explainer: dict[str, Any] | None = None,
        predictor: dict[str, Any] | None = None,
        transformer: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            canary (list[Any]): <no description>
            explainer (dict[str, Any]): <no description>
            predictor (dict[str, Any]) (required): <no description>
            transformer (dict[str, Any]): <no description>
        """
        super().__init__(**kwargs)
        self.canary = canary
        self.explainer = explainer
        self.predictor = predictor
        self.transformer = transformer

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.canary is not None:
            spec["canary"] = self.canary
        if self.explainer is not None:
            spec["explainer"] = self.explainer
        spec["predictor"] = self.predictor
        if self.transformer is not None:
            spec["transformer"] = self.transformer
        if spec:
            resource["spec"] = spec

        return resource
