# Generated by resource-generator — do not edit manually.
"""Infrastructure resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.cluster_scoped_resource import ClusterScopedResource


class Infrastructure(ClusterScopedResource):
    """Infrastructure holds cluster-wide information about Infrastructure.

    The canonical name is ``cluster``. Compatibility level 1: Stable within a major release
    for a minimum of 12 months or 3 minor releases (whichever is longer).
    """

    api_group: str = "config.openshift.io"
    api_version: str = "v1"

    def __init__(
        self,
        cloud_config: dict[str, Any] | None = None,
        platform_spec: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            cloud_config (dict[str, Any]): cloudConfig is a reference to a ConfigMap
                containing the cloud provider configuration file.
            platform_spec (dict[str, Any]): platformSpec holds desired information specific
                to the underlying infrastructure provider.
        """
        super().__init__(**kwargs)
        self.cloud_config = cloud_config
        self.platform_spec = platform_spec

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.cloud_config is not None:
            spec["cloudConfig"] = self.cloud_config
        if self.platform_spec is not None:
            spec["platformSpec"] = self.platform_spec
        if spec:
            resource["spec"] = spec

        return resource
