# Generated by resource-generator — do not edit manually.
"""Job resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class Job(NamespaceScopedResource):
    """Job represents the configuration of a single job."""

    api_group: str = "batch"
    api_version: str = "v1"

    def __init__(
        self,
        active_deadline_seconds: int | None = None,
        backoff_limit: int | None = None,
        backoff_limit_per_index: int | None = None,
        completion_mode: str | None = None,
        completions: int | None = None,
        managed_by: str | None = None,
        manual_selector: bool | None = None,
        max_failed_indexes: int | None = None,
        parallelism: int | None = None,
        pod_failure_policy: dict[str, Any] | None = None,
        pod_replacement_policy: str | None = None,
        selector: dict[str, Any] | None = None,
        success_policy: dict[str, Any] | None = None,
        suspend: bool | None = None,
        template: dict[str, Any] | None = None,
        ttl_seconds_after_finished: int | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            active_deadline_seconds (int): Specifies the duration in seconds
                relative to the startTime that the job may be continuously
                active before the system tr
            backoff_limit (int): Specifies the number of retries before
                marking this job failed. Defaults to 6
            backoff_limit_per_index (int): Specifies the limit for the number
                of retries within an index before marking this index as
                failed. When enabled the numb
            completion_mode (str): completionMode specifies how Pod
                completions are tracked. It can be `NonIndexed` (default)
                or `Indexed`. `NonIndexed` me
            completions (int): Specifies the desired number of successfully
                finished pods the job should be run with. Setting to null
                means that the s
            managed_by (str): ManagedBy field indicates the controller that
                manages a Job. The k8s Job controller reconciles jobs
                which don't have thi
            manual_selector (bool): manualSelector controls generation of
                pod labels and pod selectors. Leave `manualSelector` unset
                unless you are certain
            max_failed_indexes (int): Specifies the maximal number of failed
                indexes before marking the Job as failed, when
                backoffLimitPerIndex is set. Once
            parallelism (int): Specifies the maximum desired number of pods
                the job should run at any given time. The actual number of
                pods running in
            pod_failure_policy (dict[str, Any]): Specifies the policy of
                handling failed pods. In particular, it allows to specify
                the set of actions and conditions whic
            pod_replacement_policy (str): podReplacementPolicy specifies
                when to create replacement Pods. Possible values are:
                - TerminatingOrFailed means that we
            selector (dict[str, Any]): A label query over pods that should
                match the pod count. Normally, the system sets this field
                for you. More info: https:
            success_policy (dict[str, Any]): successPolicy specifies the
                policy when the Job can be declared as succeeded. If empty,
                the default behavior applies - t
            suspend (bool): suspend specifies whether the Job controller
                should create Pods or not. If a Job is created with suspend
                set to true, no
            template (dict[str, Any]) (required): Describes the pod that
                will be created when executing a job. The only allowed
                template.spec.restartPolicy values are "Ne
            ttl_seconds_after_finished (int): ttlSecondsAfterFinished limits
                the lifetime of a Job that has finished execution (either
                Complete or Failed). If this fi
        """
        super().__init__(**kwargs)
        self.active_deadline_seconds = active_deadline_seconds
        self.backoff_limit = backoff_limit
        self.backoff_limit_per_index = backoff_limit_per_index
        self.completion_mode = completion_mode
        self.completions = completions
        self.managed_by = managed_by
        self.manual_selector = manual_selector
        self.max_failed_indexes = max_failed_indexes
        self.parallelism = parallelism
        self.pod_failure_policy = pod_failure_policy
        self.pod_replacement_policy = pod_replacement_policy
        self.selector = selector
        self.success_policy = success_policy
        self.suspend = suspend
        self.template = template
        self.ttl_seconds_after_finished = ttl_seconds_after_finished

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.active_deadline_seconds is not None:
            spec["activeDeadlineSeconds"] = self.active_deadline_seconds
        if self.backoff_limit is not None:
            spec["backoffLimit"] = self.backoff_limit
        if self.backoff_limit_per_index is not None:
            spec["backoffLimitPerIndex"] = self.backoff_limit_per_index
        if self.completion_mode is not None:
            spec["completionMode"] = self.completion_mode
        if self.completions is not None:
            spec["completions"] = self.completions
        if self.managed_by is not None:
            spec["managedBy"] = self.managed_by
        if self.manual_selector is not None:
            spec["manualSelector"] = self.manual_selector
        if self.max_failed_indexes is not None:
            spec["maxFailedIndexes"] = self.max_failed_indexes
        if self.parallelism is not None:
            spec["parallelism"] = self.parallelism
        if self.pod_failure_policy is not None:
            spec["podFailurePolicy"] = self.pod_failure_policy
        if self.pod_replacement_policy is not None:
            spec["podReplacementPolicy"] = self.pod_replacement_policy
        if self.selector is not None:
            spec["selector"] = self.selector
        if self.success_policy is not None:
            spec["successPolicy"] = self.success_policy
        if self.suspend is not None:
            spec["suspend"] = self.suspend
        spec["template"] = self.template
        if self.ttl_seconds_after_finished is not None:
            spec["ttlSecondsAfterFinished"] = self.ttl_seconds_after_finished
        if spec:
            resource["spec"] = spec

        return resource
