# Generated by resource-generator — do not edit manually.
"""ModelRegistry resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class ModelRegistry(NamespaceScopedResource):
    """ModelRegistry is the Schema for the modelregistries API"""

    api_group: str = "modelregistry.opendatahub.io"
    api_version: str = "v1beta1"

    def __init__(
        self,
        downgrade_db_schema_version: int | None = None,
        enable_database_upgrade: bool | None = None,
        grpc: dict[str, Any] | None = None,
        kube_rbac_proxy: dict[str, Any] | None = None,
        mysql: dict[str, Any] | None = None,
        oauth_proxy: dict[str, Any] | None = None,
        postgres: dict[str, Any] | None = None,
        rest: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            downgrade_db_schema_version (int): Database downgrade schema version value. If set,
                the database schema version is downgraded to the set value during initialization.
            enable_database_upgrade (bool): Flag specifying database upgrade option. If set to
                true, it enables database migration during initialization.
            grpc (dict[str, Any]): Deprecated: Configuration for gRPC endpoint is deprecated
                and will be removed in a future release.
            kube_rbac_proxy (dict[str, Any]): kube-rbac-proxy configuration options
            mysql (dict[str, Any]): MySQL configuration options
            oauth_proxy (dict[str, Any]): OpenShift OAuth proxy configuration options
            postgres (dict[str, Any]): PostgreSQL configuration options
            rest (dict[str, Any]) (required): Configuration for REST endpoint
        """
        super().__init__(**kwargs)
        self.downgrade_db_schema_version = downgrade_db_schema_version
        self.enable_database_upgrade = enable_database_upgrade
        self.grpc = grpc
        self.kube_rbac_proxy = kube_rbac_proxy
        self.mysql = mysql
        self.oauth_proxy = oauth_proxy
        self.postgres = postgres
        self.rest = rest

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.downgrade_db_schema_version is not None:
            spec["downgrade_db_schema_version"] = self.downgrade_db_schema_version
        if self.enable_database_upgrade is not None:
            spec["enable_database_upgrade"] = self.enable_database_upgrade
        if self.grpc is not None:
            spec["grpc"] = self.grpc
        if self.kube_rbac_proxy is not None:
            spec["kubeRBACProxy"] = self.kube_rbac_proxy
        if self.mysql is not None:
            spec["mysql"] = self.mysql
        if self.oauth_proxy is not None:
            spec["oauthProxy"] = self.oauth_proxy
        if self.postgres is not None:
            spec["postgres"] = self.postgres
        spec["rest"] = self.rest
        if spec:
            resource["spec"] = spec

        return resource
