# Generated by resource-generator — do not edit manually.
"""ModelRegistry resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.cluster_scoped_resource import ClusterScopedResource


class ModelRegistry(ClusterScopedResource):
    """ModelRegistry is the Schema for the modelregistries API"""

    api_group: str = "components.platform.opendatahub.io"
    api_version: str = "v1alpha1"

    def __init__(
        self,
        gateway: dict[str, Any] | None = None,
        registries_namespace: str | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            gateway (dict[str, Any]): Gateway configuration for model registry ingress
                (synced from GatewayConfig by the DSC controller).
            registries_namespace (str): Namespace for model registries to be installed,
                configurable only once when model registry is enabled.
        """
        super().__init__(**kwargs)
        self.gateway = gateway
        self.registries_namespace = registries_namespace

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.gateway is not None:
            spec["gateway"] = self.gateway
        if self.registries_namespace is not None:
            spec["registriesNamespace"] = self.registries_namespace
        if spec:
            resource["spec"] = spec

        return resource
