# Generated by resource-generator — do not edit manually.
"""Namespace resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.cluster_scoped_resource import ClusterScopedResource


class Namespace(ClusterScopedResource):
    """Namespace provides a scope for Names. Use of multiple namespaces is optional."""

    def __init__(
        self,
        finalizers: list[str] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            finalizers (list[str]): Finalizers is an opaque list of values that must be empty
                to permanently remove object from storage.
        """
        super().__init__(**kwargs)
        self.finalizers = finalizers

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.finalizers is not None:
            spec["finalizers"] = self.finalizers
        if spec:
            resource["spec"] = spec

        return resource
