# Generated by resource-generator — do not edit manually.
"""NetworkPolicy resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class NetworkPolicy(NamespaceScopedResource):
    """NetworkPolicy describes what network traffic is allowed for a set of Pods"""

    api_group: str = "networking.k8s.io"
    api_version: str = "v1"

    def __init__(
        self,
        egress: list[Any] | None = None,
        ingress: list[Any] | None = None,
        pod_selector: dict[str, Any] | None = None,
        policy_types: list[str] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            egress (list[Any]): egress is a list of egress rules to be applied to the
                selected pods. Outgoing traffic is allowed if there are no NetworkPolicies.
            ingress (list[Any]): ingress is a list of ingress rules to be applied to the
                selected pods. Traffic is allowed to a pod if there are no NetworkPolicies.
            pod_selector (dict[str, Any]) (required): podSelector selects the pods to which
                this NetworkPolicy object applies.
            policy_types (list[str]): policyTypes is a list of rule types that the
                NetworkPolicy relates to. Valid options are ["Ingress"], ["Egress"], or both.
        """
        super().__init__(**kwargs)
        self.egress = egress
        self.ingress = ingress
        self.pod_selector = pod_selector
        self.policy_types = policy_types

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.egress is not None:
            spec["egress"] = self.egress
        if self.ingress is not None:
            spec["ingress"] = self.ingress
        spec["podSelector"] = self.pod_selector
        if self.policy_types is not None:
            spec["policyTypes"] = self.policy_types
        if spec:
            resource["spec"] = spec

        return resource
