# Generated by resource-generator — do not edit manually.
"""Node resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.cluster_scoped_resource import ClusterScopedResource


class Node(ClusterScopedResource):
    """Node is a worker node in Kubernetes. Each node will have a unique identifier in the cache (i.e. in etcd)."""

    def __init__(
        self,
        config_source: dict[str, Any] | None = None,
        external_id: str | None = None,
        pod_cidr: str | None = None,
        pod_cid_rs: list[str] | None = None,
        provider_id: str | None = None,
        taints: list[Any] | None = None,
        unschedulable: bool | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            config_source (dict[str, Any]): Deprecated: Previously used to specify the source
                of the node's configuration for the DynamicKubeletConfig feature.
            external_id (str): Deprecated. Not all kubelets will set this field.
                Remove field after 1.13. see: https://issues.k8s.io/61966
            pod_cidr (str): PodCIDR represents the pod IP range assigned to the node.
            pod_cid_rs (list[str]): podCIDRs represents the IP ranges assigned to the node
                for usage by Pods on that node.
            provider_id (str): ID of the node assigned by the cloud provider in the format:
                ProviderName://ProviderSpecificNodeID.
            taints (list[Any]): If specified, the node's taints.
            unschedulable (bool): Unschedulable controls node schedulability of new pods.
                By default, node is schedulable.
        """
        super().__init__(**kwargs)
        self.config_source = config_source
        self.external_id = external_id
        self.pod_cidr = pod_cidr
        self.pod_cid_rs = pod_cid_rs
        self.provider_id = provider_id
        self.taints = taints
        self.unschedulable = unschedulable

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.config_source is not None:
            spec["configSource"] = self.config_source
        if self.external_id is not None:
            spec["externalID"] = self.external_id
        if self.pod_cidr is not None:
            spec["podCIDR"] = self.pod_cidr
        if self.pod_cid_rs is not None:
            spec["podCIDRs"] = self.pod_cid_rs
        if self.provider_id is not None:
            spec["providerID"] = self.provider_id
        if self.taints is not None:
            spec["taints"] = self.taints
        if self.unschedulable is not None:
            spec["unschedulable"] = self.unschedulable
        if spec:
            resource["spec"] = spec

        return resource
