# Generated by resource-generator — do not edit manually.
"""OAuth resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.cluster_scoped_resource import ClusterScopedResource


class OAuth(ClusterScopedResource):
    """OAuth holds cluster-wide information about OAuth.

    The canonical name is ``cluster``. It is used to configure the integrated OAuth server.
    This configuration is only honored when the top level Authentication config has type set
    to IntegratedOAuth. Compatibility level 1: Stable within a major release for a minimum
    of 12 months or 3 minor releases (whichever is longer).
    """

    api_group: str = "config.openshift.io"
    api_version: str = "v1"

    def __init__(
        self,
        identity_providers: list[Any] | None = None,
        templates: dict[str, Any] | None = None,
        token_config: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            identity_providers (list[Any]): identityProviders is an ordered list of ways
                for a user to identify themselves. When this list is empty, no identities are provisioned.
            templates (dict[str, Any]): templates allow you to customize pages like the login page.
            token_config (dict[str, Any]): tokenConfig contains options for authorization and access tokens
        """
        super().__init__(**kwargs)
        self.identity_providers = identity_providers
        self.templates = templates
        self.token_config = token_config

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.identity_providers is not None:
            spec["identityProviders"] = self.identity_providers
        if self.templates is not None:
            spec["templates"] = self.templates
        if self.token_config is not None:
            spec["tokenConfig"] = self.token_config
        if spec:
            resource["spec"] = spec

        return resource
