# Generated by resource-generator — do not edit manually.
"""PersistentVolumeClaim resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class PersistentVolumeClaim(NamespaceScopedResource):
    """PersistentVolumeClaim is a user's request for and claim to a persistent volume"""

    def __init__(
        self,
        access_modes: list[str] | None = None,
        data_source: dict[str, Any] | None = None,
        data_source_ref: dict[str, Any] | None = None,
        resources: dict[str, Any] | None = None,
        selector: dict[str, Any] | None = None,
        storage_class_name: str | None = None,
        volume_attributes_class_name: str | None = None,
        volume_mode: str | None = None,
        volume_name: str | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            access_modes (list[str]): accessModes for the volume (e.g., ["ReadWriteOnce"]).
            resources (dict[str, Any]): resources.requests.storage for size (e.g., {"requests": {"storage": "3Gi"}}).
        """
        super().__init__(**kwargs)
        self.access_modes = access_modes
        self.data_source = data_source
        self.data_source_ref = data_source_ref
        self.resources = resources
        self.selector = selector
        self.storage_class_name = storage_class_name
        self.volume_attributes_class_name = volume_attributes_class_name
        self.volume_mode = volume_mode
        self.volume_name = volume_name

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.access_modes is not None:
            spec["accessModes"] = self.access_modes
        if self.data_source is not None:
            spec["dataSource"] = self.data_source
        if self.data_source_ref is not None:
            spec["dataSourceRef"] = self.data_source_ref
        if self.resources is not None:
            spec["resources"] = self.resources
        if self.selector is not None:
            spec["selector"] = self.selector
        if self.storage_class_name is not None:
            spec["storageClassName"] = self.storage_class_name
        if self.volume_attributes_class_name is not None:
            spec["volumeAttributesClassName"] = self.volume_attributes_class_name
        if self.volume_mode is not None:
            spec["volumeMode"] = self.volume_mode
        if self.volume_name is not None:
            spec["volumeName"] = self.volume_name
        if spec:
            resource["spec"] = spec

        return resource
