# Generated by resource-generator — do not edit manually.
"""ReferenceGrant resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class ReferenceGrant(NamespaceScopedResource):
    """ReferenceGrant identifies kinds of resources in other namespaces that are trusted to reference the
    specified kinds of resources in the same namespace as the policy. Each ReferenceGrant can be used to
    represent a unique trust relationship. Additional Reference Grants can be used to add to the set of
    trusted sources of inbound references for the namespace they are defined within. All cross-namespace
    references in Gateway API (with the exception of cross-namespace Gateway-route attachment) require a
    ReferenceGrant. ReferenceGrant is a form of runtime verification allowing users to assert which
    cross-namespace object references are permitted. Implementations that support ReferenceGrant MUST NOT
    permit cross-namespace references which have no grant, and MUST respond to the removal of a grant by
    revoking the access that the grant allowed.
    """

    api_group: str = "gateway.networking.k8s.io"
    api_version: str = "v1beta1"

    def __init__(
        self,
        from_: list[Any] | None = None,
        to: list[Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            from_ (list[Any]) (required): From describes the trusted namespaces and kinds that can
                reference the resources described in "To". Each entry in this list MUST be considered
                to be an additional place that references can be valid from, or to put this another way,
                entries MUST be combined using OR.
            to (list[Any]) (required): To describes the resources that may be referenced by the
                resources described in "From". Each entry in this list MUST be considered to be an
                additional place that references can be valid to, or to put this another way, entries
                MUST be combined using OR.
        """
        super().__init__(**kwargs)
        self.from_ = from_
        self.to = to

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        spec["from"] = self.from_
        spec["to"] = self.to
        if spec:
            resource["spec"] = spec

        return resource
