# Generated by resource-generator — do not edit manually.
"""Role resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class Role(NamespaceScopedResource):
    """Role is a namespaced, logical grouping of PolicyRules that can be referenced as a unit by a RoleBinding."""

    api_group: str = "rbac.authorization.k8s.io"
    api_version: str = "v1"

    def __init__(
        self,
        rules: list[Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            rules (list[Any]): Rules holds all the PolicyRules for this Role
        """
        super().__init__(**kwargs)
        self.rules = rules

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        if self.rules is not None:
            resource["rules"] = self.rules

        return resource
