# Generated by resource-generator — do not edit manually.
"""RoleBinding resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class RoleBinding(NamespaceScopedResource):
    """RoleBinding references a role, but does not contain it.

    It can reference a Role in the same namespace or a ClusterRole in the global namespace.
    It adds who information via Subjects and namespace information by which namespace it exists in.
    RoleBindings in a given namespace only have effect in that namespace.
    """

    api_group: str = "rbac.authorization.k8s.io"
    api_version: str = "v1"

    def __init__(
        self,
        role_ref: dict[str, Any] | None = None,
        subjects: list[Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            role_ref (dict[str, Any]) (required): RoleRef can reference a Role in the current namespace or a
                ClusterRole in the global namespace. If the RoleRef cannot be resolved.
            subjects (list[Any]): Subjects holds references to the objects the role applies to.
        """
        super().__init__(**kwargs)
        self.role_ref = role_ref
        self.subjects = subjects

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        resource["roleRef"] = self.role_ref
        if self.subjects is not None:
            resource["subjects"] = self.subjects

        return resource
