# Generated by resource-generator — do not edit manually.
"""Route resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class Route(NamespaceScopedResource):
    """A route allows developers to expose services through an HTTP(S) aware load balancing layer.

    The route may further specify TLS options and a certificate, or specify a public CNAME
    that the router should also accept for HTTP and HTTPS traffic. Routers usually talk
    directly to the service endpoints. Once a route is created, the ``host`` field may not
    be changed. Compatibility level 1: Stable within a major release for a minimum of
    12 months or 3 minor releases (whichever is longer).
    """

    api_group: str = "route.openshift.io"
    api_version: str = "v1"

    def __init__(
        self,
        alternate_backends: list[Any] | None = None,
        host: str | None = None,
        http_headers: dict[str, Any] | None = None,
        path: str | None = None,
        port: dict[str, Any] | None = None,
        subdomain: str | None = None,
        tls: dict[str, Any] | None = None,
        to: dict[str, Any] | None = None,
        wildcard_policy: str | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            alternate_backends (list[Any]): alternateBackends allows up to 3 additional
                backends to be assigned to the route. Only the Service kind is allowed.
            host (str): host is an alias/DNS that points to the service. Optional. If not
                specified a route name will typically be automatically chosen.
            http_headers (dict[str, Any]): httpHeaders defines policy for HTTP headers.
            path (str): path that the router watches for, to route traffic to the service.
            port (dict[str, Any]): If specified, the port to be used by the router. Most
                routers will use all endpoints exposed by the service by default.
            subdomain (str): subdomain is a DNS subdomain that is requested within the
                ingress controller's domain.
            tls (dict[str, Any]): The tls field provides the ability to configure
                certificates and termination for the route.
            to (dict[str, Any]) (required): to is an object the route should use as the
                primary backend. Only the Service kind is allowed.
            wildcard_policy (str): Wildcard policy if any for the route. Currently only
                'Subdomain' or 'None' is allowed.
        """
        super().__init__(**kwargs)
        self.alternate_backends = alternate_backends
        self.host = host
        self.http_headers = http_headers
        self.path = path
        self.port = port
        self.subdomain = subdomain
        self.tls = tls
        self.to = to
        self.wildcard_policy = wildcard_policy

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.alternate_backends is not None:
            spec["alternateBackends"] = self.alternate_backends
        if self.host is not None:
            spec["host"] = self.host
        if self.http_headers is not None:
            spec["httpHeaders"] = self.http_headers
        if self.path is not None:
            spec["path"] = self.path
        if self.port is not None:
            spec["port"] = self.port
        if self.subdomain is not None:
            spec["subdomain"] = self.subdomain
        if self.tls is not None:
            spec["tls"] = self.tls
        spec["to"] = self.to
        if self.wildcard_policy is not None:
            spec["wildcardPolicy"] = self.wildcard_policy
        if spec:
            resource["spec"] = spec

        return resource
