# Generated by resource-generator — do not edit manually.
"""Secret resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class Secret(NamespaceScopedResource):
    """Secret holds secret data of a certain type.

    The total bytes of the values in the Data field must be less than MaxSecretSize bytes.
    """

    def __init__(
        self,
        data: dict[str, str] | None = None,
        immutable: bool | None = None,
        string_data: dict[str, str] | None = None,
        type_: str | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            data (dict[str, str]): Data contains the secret data. Each key must consist
                of alphanumeric characters, '-', '_' or '.'.
            immutable (bool): Immutable, if set to true, ensures that data stored in
                the Secret cannot be updated (only object metadata can be modified).
            string_data (dict[str, str]): stringData allows specifying non-binary secret
                data in string form. It is provided as a write-only input field.
            type_ (str): Used to facilitate programmatic handling of secret data.
        """
        super().__init__(**kwargs)
        self.data = data
        self.immutable = immutable
        self.string_data = string_data
        self.type_ = type_

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        if self.data is not None:
            resource["data"] = self.data
        if self.immutable is not None:
            resource["immutable"] = self.immutable
        if self.string_data is not None:
            resource["stringData"] = self.string_data
        if self.type_ is not None:
            resource["type"] = self.type_

        return resource
