# Generated by resource-generator — do not edit manually.
"""ServingRuntime resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class ServingRuntime(NamespaceScopedResource):
    """<empty>"""

    api_version: str = "v1alpha1"

    def __init__(
        self,
        affinity: dict[str, Any] | None = None,
        annotations: dict[str, str] | None = None,
        built_in_adapter: dict[str, Any] | None = None,
        containers: list[Any] | None = None,
        disabled: bool | None = None,
        grpc_data_endpoint: str | None = None,
        grpc_endpoint: str | None = None,
        host_ipc: bool | None = None,
        http_data_endpoint: str | None = None,
        image_pull_secrets: list[Any] | None = None,
        labels: dict[str, str] | None = None,
        multi_model: bool | None = None,
        node_selector: dict[str, str] | None = None,
        protocol_versions: list[str] | None = None,
        replicas: int | None = None,
        resource_claims: list[Any] | None = None,
        scheduler_name: str | None = None,
        storage_helper: dict[str, Any] | None = None,
        supported_model_formats: list[Any] | None = None,
        tolerations: list[Any] | None = None,
        volumes: list[Any] | None = None,
        worker_spec: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            affinity (dict[str, Any]): <no description>
            annotations (dict[str, str]): <no description>
            built_in_adapter (dict[str, Any]): <no description>
            containers (list[Any]) (required): <no description>
            disabled (bool): <no description>
            grpc_data_endpoint (str): <no description>
            grpc_endpoint (str): <no description>
            host_ipc (bool): <no description>
            http_data_endpoint (str): <no description>
            image_pull_secrets (list[Any]): <no description>
            labels (dict[str, str]): <no description>
            multi_model (bool): <no description>
            node_selector (dict[str, str]): <no description>
            protocol_versions (list[str]): <no description>
            replicas (int): <no description>
            resource_claims (list[Any]): <no description>
            scheduler_name (str): <no description>
            storage_helper (dict[str, Any]): <no description>
            supported_model_formats (list[Any]): <no description>
            tolerations (list[Any]): <no description>
            volumes (list[Any]): <no description>
            worker_spec (dict[str, Any]): <no description>
        """
        super().__init__(**kwargs)
        self.affinity = affinity
        self.annotations = annotations
        self.built_in_adapter = built_in_adapter
        self.containers = containers
        self.disabled = disabled
        self.grpc_data_endpoint = grpc_data_endpoint
        self.grpc_endpoint = grpc_endpoint
        self.host_ipc = host_ipc
        self.http_data_endpoint = http_data_endpoint
        self.image_pull_secrets = image_pull_secrets
        self.labels = labels
        self.multi_model = multi_model
        self.node_selector = node_selector
        self.protocol_versions = protocol_versions
        self.replicas = replicas
        self.resource_claims = resource_claims
        self.scheduler_name = scheduler_name
        self.storage_helper = storage_helper
        self.supported_model_formats = supported_model_formats
        self.tolerations = tolerations
        self.volumes = volumes
        self.worker_spec = worker_spec

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.affinity is not None:
            spec["affinity"] = self.affinity
        if self.annotations is not None:
            spec["annotations"] = self.annotations
        if self.built_in_adapter is not None:
            spec["builtInAdapter"] = self.built_in_adapter
        spec["containers"] = self.containers
        if self.disabled is not None:
            spec["disabled"] = self.disabled
        if self.grpc_data_endpoint is not None:
            spec["grpcDataEndpoint"] = self.grpc_data_endpoint
        if self.grpc_endpoint is not None:
            spec["grpcEndpoint"] = self.grpc_endpoint
        if self.host_ipc is not None:
            spec["hostIPC"] = self.host_ipc
        if self.http_data_endpoint is not None:
            spec["httpDataEndpoint"] = self.http_data_endpoint
        if self.image_pull_secrets is not None:
            spec["imagePullSecrets"] = self.image_pull_secrets
        if self.labels is not None:
            spec["labels"] = self.labels
        if self.multi_model is not None:
            spec["multiModel"] = self.multi_model
        if self.node_selector is not None:
            spec["nodeSelector"] = self.node_selector
        if self.protocol_versions is not None:
            spec["protocolVersions"] = self.protocol_versions
        if self.replicas is not None:
            spec["replicas"] = self.replicas
        if self.resource_claims is not None:
            spec["resourceClaims"] = self.resource_claims
        if self.scheduler_name is not None:
            spec["schedulerName"] = self.scheduler_name
        if self.storage_helper is not None:
            spec["storageHelper"] = self.storage_helper
        if self.supported_model_formats is not None:
            spec["supportedModelFormats"] = self.supported_model_formats
        if self.tolerations is not None:
            spec["tolerations"] = self.tolerations
        if self.volumes is not None:
            spec["volumes"] = self.volumes
        if self.worker_spec is not None:
            spec["workerSpec"] = self.worker_spec
        if spec:
            resource["spec"] = spec

        return resource
