# Generated by resource-generator — do not edit manually.
"""ServiceAccount resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources._sync import _run_sync
from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource
from utilities.openshift_resources.oc import run_oc
from utilities.openshift_resources.resource_dict import ResourceDict


class ServiceAccount(NamespaceScopedResource):
    """ServiceAccount binds together a name, a principal, and a set of secrets.

    The name is understood by users and perhaps by peripheral systems for an identity.
    The principal can be authenticated and authorized.
    """

    def __init__(
        self,
        automount_service_account_token: bool | None = None,
        image_pull_secrets: list[Any] | None = None,
        secrets: list[Any] | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            automount_service_account_token (bool): AutomountServiceAccountToken indicates
                whether pods running as this service account should have an API token
                automatically mounted.
            image_pull_secrets (list[Any]): ImagePullSecrets is a list of references to
                secrets in the same namespace to use for pulling any images in pods.
            secrets (list[Any]): Secrets is a list of the secrets in the same namespace
                that pods running using this ServiceAccount are allowed to use.
        """
        super().__init__(**kwargs)
        self.automount_service_account_token = automount_service_account_token
        self.image_pull_secrets = image_pull_secrets
        self.secrets = secrets

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        if self.automount_service_account_token is not None:
            resource["automountServiceAccountToken"] = self.automount_service_account_token
        if self.image_pull_secrets is not None:
            resource["imagePullSecrets"] = self.image_pull_secrets
        if self.secrets is not None:
            resource["secrets"] = self.secrets

        return resource

    async def _async_create_service_account_token(self, expiration_seconds: int = 86400) -> dict[str, Any]:
        """Create a token for this service account via oc create token."""
        result = await run_oc(
            args=["create", "token", self.name, "-n", self.namespace, f"--duration={expiration_seconds}s"],
        )
        return ResourceDict({"status": {"token": result.stdout.strip()}})  # noqa: FCN001

    def create_service_account_token(self, expiration_seconds: int = 86400) -> dict[str, Any]:
        return _run_sync(coro=self._async_create_service_account_token(expiration_seconds=expiration_seconds))
