# Generated by resource-generator — do not edit manually.
"""Service resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class Service(NamespaceScopedResource):
    """Service is a named abstraction of software service (for example, mysql) consisting of local port
    (for example 3306) that the proxy listens on, and the selector that determines which pods will answer
    requests sent through the proxy.
    """

    def __init__(
        self,
        allocate_load_balancer_node_ports: bool | None = None,
        cluster_ip: str | None = None,
        cluster_i_ps: list[str] | None = None,
        external_i_ps: list[str] | None = None,
        external_name: str | None = None,
        external_traffic_policy: str | None = None,
        health_check_node_port: int | None = None,
        internal_traffic_policy: str | None = None,
        ip_families: list[str] | None = None,
        ip_family_policy: str | None = None,
        load_balancer_class: str | None = None,
        load_balancer_ip: str | None = None,
        load_balancer_source_ranges: list[str] | None = None,
        ports: list[Any] | None = None,
        publish_not_ready_addresses: bool | None = None,
        selector: dict[str, str] | None = None,
        session_affinity: str | None = None,
        session_affinity_config: dict[str, Any] | None = None,
        traffic_distribution: str | None = None,
        type_: str | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            allocate_load_balancer_node_ports (bool): allocateLoadBalancerNodePorts defines if
                NodePorts will be automatically allocated for services with type LoadBalancer.
            cluster_ip (str): clusterIP is the IP address of the service and is usually assigned
                randomly. If an address is specified manually, is in-range, and is not in use.
            cluster_i_ps (list[str]): ClusterIPs is a list of IP addresses assigned to this
                service, and are usually assigned randomly.
            external_i_ps (list[str]): externalIPs is a list of IP addresses for which nodes in
                the cluster will also accept traffic for this service.
            external_name (str): externalName is the external reference that discovery mechanisms
                will return as an alias for this service (e.g. a DNS CNAME record).
            external_traffic_policy (str): externalTrafficPolicy describes how nodes distribute
                service traffic they receive on one of the Service's "externally-facing" addresses.
            health_check_node_port (int): healthCheckNodePort specifies the healthcheck nodePort
                for the service. This only applies when type is set to LoadBalancer.
            internal_traffic_policy (str): InternalTrafficPolicy describes how nodes distribute
                service traffic they receive on the ClusterIP.
            ip_families (list[str]): IPFamilies is a list of IP families (e.g. IPv4, IPv6)
                assigned to this service.
            ip_family_policy (str): IPFamilyPolicy represents the dual-stack-ness requested or
                required by this Service.
            load_balancer_class (str): loadBalancerClass is the class of the load balancer
                implementation this Service belongs to.
            load_balancer_ip (str): Only applies to Service Type: LoadBalancer. This feature
                depends on whether the underlying cloud-provider supports specifying this field.
            load_balancer_source_ranges (list[str]): If specified and supported by the platform,
                this will restrict traffic through the cloud-provider load-balancer.
            ports (list[Any]): The list of ports that are exposed by this service.
            publish_not_ready_addresses (bool): publishNotReadyAddresses indicates that any agent
                which deals with endpoints for this Service should disregard any indications of
                readiness.
            selector (dict[str, str]): Route service traffic to pods with label keys and values
                matching this selector.
            session_affinity (str): Supports "ClientIP" and "None". Used to maintain session
                affinity.
            session_affinity_config (dict[str, Any]): sessionAffinityConfig contains the
                configurations of session affinity.
            traffic_distribution (str): TrafficDistribution offers a way to express preferences
                for how traffic is distributed to Service endpoints.
            type_ (str): type determines how the Service is exposed. Defaults to ClusterIP.
                Valid options are ExternalName, ClusterIP, NodePort, and LoadBalancer.
        """
        super().__init__(**kwargs)
        self.allocate_load_balancer_node_ports = allocate_load_balancer_node_ports
        self.cluster_ip = cluster_ip
        self.cluster_i_ps = cluster_i_ps
        self.external_i_ps = external_i_ps
        self.external_name = external_name
        self.external_traffic_policy = external_traffic_policy
        self.health_check_node_port = health_check_node_port
        self.internal_traffic_policy = internal_traffic_policy
        self.ip_families = ip_families
        self.ip_family_policy = ip_family_policy
        self.load_balancer_class = load_balancer_class
        self.load_balancer_ip = load_balancer_ip
        self.load_balancer_source_ranges = load_balancer_source_ranges
        self.ports = ports
        self.publish_not_ready_addresses = publish_not_ready_addresses
        self.selector = selector
        self.session_affinity = session_affinity
        self.session_affinity_config = session_affinity_config
        self.traffic_distribution = traffic_distribution
        self.type_ = type_

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.allocate_load_balancer_node_ports is not None:
            spec["allocateLoadBalancerNodePorts"] = self.allocate_load_balancer_node_ports
        if self.cluster_ip is not None:
            spec["clusterIP"] = self.cluster_ip
        if self.cluster_i_ps is not None:
            spec["clusterIPs"] = self.cluster_i_ps
        if self.external_i_ps is not None:
            spec["externalIPs"] = self.external_i_ps
        if self.external_name is not None:
            spec["externalName"] = self.external_name
        if self.external_traffic_policy is not None:
            spec["externalTrafficPolicy"] = self.external_traffic_policy
        if self.health_check_node_port is not None:
            spec["healthCheckNodePort"] = self.health_check_node_port
        if self.internal_traffic_policy is not None:
            spec["internalTrafficPolicy"] = self.internal_traffic_policy
        if self.ip_families is not None:
            spec["ipFamilies"] = self.ip_families
        if self.ip_family_policy is not None:
            spec["ipFamilyPolicy"] = self.ip_family_policy
        if self.load_balancer_class is not None:
            spec["loadBalancerClass"] = self.load_balancer_class
        if self.load_balancer_ip is not None:
            spec["loadBalancerIP"] = self.load_balancer_ip
        if self.load_balancer_source_ranges is not None:
            spec["loadBalancerSourceRanges"] = self.load_balancer_source_ranges
        if self.ports is not None:
            spec["ports"] = self.ports
        if self.publish_not_ready_addresses is not None:
            spec["publishNotReadyAddresses"] = self.publish_not_ready_addresses
        if self.selector is not None:
            spec["selector"] = self.selector
        if self.session_affinity is not None:
            spec["sessionAffinity"] = self.session_affinity
        if self.session_affinity_config is not None:
            spec["sessionAffinityConfig"] = self.session_affinity_config
        if self.traffic_distribution is not None:
            spec["trafficDistribution"] = self.traffic_distribution
        if self.type_ is not None:
            spec["type"] = self.type_
        if spec:
            resource["spec"] = spec

        return resource
