# Generated by resource-generator — do not edit manually.
"""Subscription resource."""

from __future__ import annotations

from typing import Any

from utilities.openshift_resources.namespace_scoped_resource import NamespaceScopedResource


class Subscription(NamespaceScopedResource):
    """Subscription keeps operators up to date by tracking changes to Catalogs."""

    api_group: str = "operators.coreos.com"
    api_version: str = "v1alpha1"

    def __init__(
        self,
        channel: str | None = None,
        config: dict[str, Any] | None = None,
        install_plan_approval: str | None = None,
        name: str | None = None,
        source: str | None = None,
        source_namespace: str | None = None,
        starting_csv: str | None = None,
        **kwargs: Any,
    ) -> None:
        """
        Args:
            channel (str): <no description>
            config (dict[str, Any]): SubscriptionConfig contains configuration specified for a subscription.
            install_plan_approval (str): Approval is the user approval policy for an
                InstallPlan. It must be one of "Automatic" or "Manual".
            name (str) (required): <no description>
            source (str) (required): <no description>
            source_namespace (str) (required): <no description>
            starting_csv (str): <no description>
        """
        super().__init__(**kwargs)
        self.channel = channel
        self.config = config
        self.install_plan_approval = install_plan_approval
        self.name = name
        self.source = source
        self.source_namespace = source_namespace
        self.starting_csv = starting_csv

    def _build_dict(self) -> dict[str, Any]:
        resource = super()._build_dict()

        spec: dict[str, Any] = {}
        if self.channel is not None:
            spec["channel"] = self.channel
        if self.config is not None:
            spec["config"] = self.config
        if self.install_plan_approval is not None:
            spec["installPlanApproval"] = self.install_plan_approval
        spec["name"] = self.name
        spec["source"] = self.source
        spec["sourceNamespace"] = self.source_namespace
        if self.starting_csv is not None:
            spec["startingCSV"] = self.starting_csv
        if spec:
            resource["spec"] = spec

        return resource
