# Generated using https://github.com/RedHatQE/openshift-python-wrapper/blob/main/scripts/resource/README.md

from ocp_resources.resource import NamespacedResource


class EnvoyFilter(NamespacedResource):
    """
    EnvoyFilter object. Customizing Envoy configuration generated by Istio.
    """

    api_group: str = NamespacedResource.ApiGroup.NETWORKING_ISTIO_IO

    # End of generated code
