name: PR Comment Labeler

on:
  pull_request:
    types: [opened, edited]
  pull_request_comment:
    types: [created]

jobs:
  pr-comment-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add labels
        uses: actions/add-labels@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            {% if event.name == "pull_request_comment" %}
              commented-by @{{ github.event.comment.user.login }}
            {% elsif event.name == "pull_request" %}
              changed-requested @{{ github.event.sender.login }}
            {% endif %}

      - name: Remove label on new push
        uses: actions/remove-label@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: commented-by
