name: PR Size Labeler
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.lock'
      - '**/LICENSE'
      - '**/*.md'

jobs:
  label-size:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Label PR Size
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/size-labeler.yml
