name: Tox check

on:
  pull_request:

jobs:
  tox:
    name: test with ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
          - "3.12"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
      - name: Install tox
        run: uv tool install --python-preference only-managed --python 3.13 tox --with tox-uv --with tox-gh
      - name: Install Python
        if: matrix.python-version != '3.13'
        run: uv python install --python-preference only-managed ${{ matrix.python-version }}
      - name: Run tox
        run: tox
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.python-version }}
